### PR TITLE
Theme Link Fixes

### PR DESCRIPTION
**Pull request by rachelg4**
@stvstnfrd & @caesar2164

### CODE REVIEW

**Comment by caesar2164** [comment]
looks good to me 👍

**Comment by stvstnfrd** [comment]
The code changes look good and fulfill the request.

@caesar2164 While we're in here, should we make these `https` links instead of `http`?
It looks like each site has SSL enabled:
- https://open.edx.org
- https://lytics.stanford.edu/research/

**Comment by caesar2164** [comment]
good call, @stvstnfrd.

@rachelg4, would you mind adding adding two new commits each adding the appropriate 's', then we can show you how to do a fancy squash?

**Comment by rachelg4** [comment]
Changes addressed!

**Comment by caesar2164** [comment]
👍

**Comment by stvstnfrd** [comment]
+1

**Pull request merged**
