### PR TITLE
remove {account_name} translation strings

### PR DESCRIPTION
**Pull request by caesar2164**
- no other change is necessary since the {platform_name} strings are already there...

@stvstnfrd & @kluo

### CODE REVIEW

**Comment by kluo** [comment]
+1

**Comment by stvstnfrd** [comment]
How sure are we that we didn't have any forked text in those strings, besides `account_name`?

**Comment by caesar2164** [comment]
according to @kluo those strings were ONLY there because of the account_name change

**Comment by stvstnfrd** [comment]
+1

**Pull request merged**
