### PR TITLE
Modify address in terms of service

### PR DESCRIPTION
**Pull request by karandikar**
Monica requested a change of address in the terms of service from the Santa Teresa address to the Panama Mall address. This is listed on sprint-next in the backlog Trello -- I just figured it was something I could handle quickly to save time next week. @stvstnfrd @caesar2164 @mondiaz

### CODE REVIEW

**Comment by stvstnfrd** [comment]
+1

I'm guessing we need this change in SUclass and probably CME themes too?

**Comment by caesar2164** [comment]
👍

**Comment by karandikar** [comment]
Before:
image
After:
image

**Comment by mondiaz** [comment]
@karandikar @caesar2164 👍 lgtm!

**Pull request merged**
